### ISSUE TITLE
Compatibility error when using for android.

### ISSUE THREAD

**Issue by dhavrutsky** [go-ive/steam-api#12]
Is this project available for java 7? I am getting errors with compatitiblity.

**Comment by go-ive** [comment]
I'll have a look to see what specific changes need to be made. Shouldn't be that many as the codebase is quite small at the moment.

**Comment by go-ive** [comment]
Turns out it was two lines of code and some pom changes. I just released version 4.3 that should work for java 7. Can you try it out and tell me if it works for you?

**Comment by dhavrutsky** [comment]
Yep, thanks!
